import Button from "./atoms/Button";
import Heading from "./atoms/Heading";
import Text from "./atoms/Text";
import Link from "./atoms/Link";
import Image from "./atoms/Image";
import Margin from "./atoms/Margin";
import Navbar from "./atoms/Navbar";
import Menu from "./molecules/Menu";
import Label from "./molecules/Label";
export { Button, Heading, Text, Link, Image, Margin, Menu, Navbar, Label };
